services:
  # Service pour l'application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  # Service pour MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ticket_system
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # Service pour Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

# Volumes pour MySQL
volumes:
  db-data:

# Réseau pour connecter les services
networks:
  app-network:
    driver: bridge